---
name: Get Deployment Status
description: Poll the deployment status 
inputs:
  project-alias:
    description: the project alias for the project you are running a deployment on
    required: true
  deployment-id:
    description: id linked to the deployment you want to get status on
    required: true
  api-key:
    description: key needed to have access to api
    required: true
  timeout-seconds:
    description: number of seconds to be running before hitting a timeout-seconds
    required: false
    default: '600'
  
runs:
  using: node16
  main: action/index.js